### ISSUE TITLE
TGC from OPhiW

### ISSUE THREAD

**Issue by amirsubba** [SMEFTsim/SMEFTsim#9]
I  am trying to create a model with OPhiW = Phi^+ Phi W^{\mu\nu} W_{\mu\nu}. literature suggest no TGC from this but after EWSB in feynrules, we do have ZWW and AWW vertex. Can you clarify on this. Thank you.

**Comment by IlariaBrivio** [comment]
Dear Amir,

this operator is equal to the W kinetic term * Phidag Phi, so TGCs naively appear when Phi takes a vev. However, they necessarily come together with a correction to the W 2-point-function that needs to be renormalized away to have canonical kinetic terms. The redefinition that removes the latter removes also the TGCs and leaves HVV vertices as the lowest order effects. The redefinition I’m referring to is the one discussed in section 2.2 of the manual https://arxiv.org/pdf/2012.11343

I hope this clarifies it.
Ilaria

**Comment by amirsubba** [comment]
It is clear now. Thank you for the clarification.
